### ISSUE TITLE
Dockerfile issues

### ISSUE THREAD

**Issue by MarleDK** [useparagon/aws-on-prem#1]
# Dockerfile issues

Hi, I think it's really nice that your are making this repository for the self-hosted version of paragon. I work at famly, and has been trying to get this up and running, but I run into some issues using the dockerfile.

1. `COPY ../ .` fails to build the docker image with:
    ```
    Step 9/10 : COPY  ../ .
    COPY failed: forbidden path outside the build context: ../ ()
    make: *** [Makefile:6: build] Error 1
    ```
    It also seems like it is maybe redundant with the `ADD . .`?
2. When I try to run `make -s deploy-infra` I get this error:
    ```
    /usr/lib/node_modules/ts-node/src/index.ts:750
        return new TSError(diagnosticText, diagnosticCodes);
               ^
    TSError: ⨯ Unable to compile TypeScript:
    scripts/cli/index.ts:8:15 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

    8 program.parse(process.argv);
                    ~~~~~~~

        at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:750:12)
        at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:754:19)
        at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:941:36)
        at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:1243:30)
        at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1370:30)
        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1374:12)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
      diagnosticText: "\x1B[96mscripts/cli/index.ts\x1B[0m:\x1B[93m8\x1B[0m:\x1B[93m15\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2580: \x1B[0mCannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.\n" +
        '\n' +
        '\x1B[7m8\x1B[0m program.parse(process.argv);\n' +
        '\x1B[7m \x1B[0m \x1B[91m              ~~~~~~~\x1B[0m\n',
      diagnosticCodes: [ 2580 ]
    }
    make: *** [Makefile:39: deploy-infra] Error 1

    ```
    I have also tried to add `npm -i --save-dev @types/node` as part of the Dockerfile, as suggested by the error, but that didn't work. And it also seems like it should be installed by `yarn install`, right? I haven't used javascript very much, and it has been some years, so I am having a bit of an issue debugging this issue myself.

Hope you can help me with these issues. And let me know, if you need anything else from me.

**Comment by ishmaelthedestroyer** [comment]
Hi @MarleDK, thanks for the detailed error logs. I believe the second error is a side effect of the first, as the NPM modules aren't being installed in the docker image which happens after the `COPY` command that's erroring out.

For the first error, I think it might be related to your Docker version or operating system. I'm running `20.10.17` on Mac `12.3.1` and it builds without error. However, it appears that the `COPY` and `ADD` commands are redundant. I've pushed a fix - can you pull the latest changes and try again?

**Comment by MarleDK** [comment]
Hi @ishmaelthedestroyer
Thank you for the help. 

I tried again, and got the same error, but I see what the issue is now. In your [makefile](https://github.com/useparagon/aws-on-prem/blob/master/Makefile) you have the following line `--mount source="$(shell pwd)",target=/usr/src/app,type=bind \` which removed what the docker image has in `/usr/src/app`, which means whatever was produced by `yarn install` in the Dockerfile. It probably works for you, as you have locally run yarn install, outside of the docker image, but if you copy this repo into some other folder, and tried to run `make build` and then `make deploy-infra`, I think you would get the error I get as well.

A quick way for me to fix it, is to remove the `--mount source`. Which I guess will also work generally well for people using the repository, but I guess for development puposes, the mount is a nice convenience. And for me I guess it would also be nice to have the things locally in the repo, for easy access.

I tested that if I do a `docker run -it --mount source="$(shell pwd)",target=/usr/src/app,type=bind yarn install`, afterwards the other commands work. So you could add this to the makefile and README

**Comment by MarleDK** [comment]
Ahh, great. Thank you :)
